runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_USER: "root"
  DB_PASS: "admin"
  DB_NAME: "retaildb"
  INSTANCE_CONNECTION_NAME: "group21cloud:us-central1:retail-instance" # Change to your instance

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
